Repository guardian/facia-tool, pull requests merged in 2025-06, with the labels that each got.

#1817 Provide a 'Use Replacement Video' toggle for cards w/ main media
  fronts-client/src/components/video/VideoControls.tsx
Labels: Pending-on-PROD, video

#1820 Allow replacement videos to be removed from a card
  fronts-client/src/components/video/VideoControls.tsx
Labels: video

#1821 Add a tooltip and warning for videos
  fronts-client/src/components/form/ArticleMetaForm.tsx
  fronts-client/src/components/icons/Icons.tsx
  fronts-client/src/components/modals/Tooltip.tsx
  fronts-client/src/components/video/VideoControls.tsx
Labels: video

#1826 Set card criteria to landscape54 image if no collection type
  fronts-client/src/components/form/ArticleMetaForm.tsx
Labels: Seen-on-PROD

#1830 Redux form prefers empty strings as undefined state
  fronts-client/src/components/FrontsEdit/__tests__/CardForm.spec.ts
  fronts-client/src/components/form/ArticleMetaForm.tsx
  fronts-client/src/util/form.ts
Labels: video

#1841 Only fetch replacement video atom if videoReplace field is set
  fronts-client/src/components/form/ArticleMetaForm.tsx
Labels: video

#1840 Fix race condition where form reinitialisation clears user edits
  fronts-client/src/components/form/ArticleMetaForm.tsx
Labels: video
